---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes

- name: Update apt config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: 20auto-upgrades
      dest: /etc/apt/apt.conf.d/20auto-upgrades
    - src: 50unattended-upgrades
      dest: /etc/apt/apt.conf.d/50unattended-upgrades


